b2wdigital/async-worker

- README.md
- asyncworker/consumer.py
- asyncworker/options.py
- asyncworker/rabbitmq/message.py
- tests/test_app.py
- tests/test_consumer.py
- tests/test_rabbitmq_message.py
Aqui temos um problema, tem até teste falhando para demonstrar.
E é o seguinte:
A partir do momento em que temos "acão padrão" para `ON_SUCCESS` e `ON_EXCEPTION` não podemos mais, dentro do handler, escolher o que será feito com cada mensagem. Por exemplo, se a ação padrão na `ON_EXCEPTION` é `REJECT` (`.reject(requeue=False)`) e o handler chama `.reject(requeue=True)`,  essa ação feita pelo handler será **desfeita** pelo asyncworker, depois que o `handler` retornar.
Isso vale para qualquer valor de `ON_SUCCESS` e `ON_EXCEPTION`.
Se formos contornar isso fazendo com que a `Message` tenha uma flag que impeça que uma segunda ação mude uma anterior, ou seja, se eu chamei `.reject(requeue=True)` uma chamada futura a `.reject(requeue=False)` será `NOOP`. Isso também é um problema pois o …
> Implementação do ON_SUCCESS e ON_EXCEPTION

- Pipfile
- Pipfile.lock
- tests/signals/handlers/test_http.py
Adicionando também um teste que faz um request real, abrindo porta e
etc. Isso pode ajudar a garantir que o handler do tipo HTTP está
funcionando corretamente.
> Atualizando aiohttp para 3.5.4

- README.md
- asyncworker/bucket.py
- asyncworker/conf.py
- asyncworker/consumer.py
- asyncworker/time.py
- tests/rabbitmq/test_rabbitmq_consumer.py
- tests/test_bucket.py
- tests/test_time.py
Hoje o async-worker trabalhar com buckets de N mensagens que permitem a possibilidade de trabalhar diretamente com esse conjunto de mensagens. Porém caso o bucket não fique cheio as mensagens ficarão travadas até que o bucket alcance esse o seu limite de mensagens.
Com essa modificação será possível fazer flush das mensagens após alguns segundos.
> Adicionando timeout para realizar flush no bucket após N segundos

- asyncworker/consumer.py
- asyncworker/options.py
- asyncworker/routes.py
- asyncworker/signals/handlers/http.py
- tests/rabbitmq/test_rabbitmq_app.py
- tests/rabbitmq/test_rabbitmq_consumer.py
- tests/sse/test_sse_app.py
- tests/test_base.py
- tests/test_routes.py
On the public API, nothing changes, so there's no need to update the docs.
Motivation: Before working on middlewares, I thought we needed the `RoutesRegistry` and the routing system to be more "solid" 
closes #64 
closes #83
> #64 -  RoutesRegistry refactoring

- setup.py
Modificado: `setup.py`
- "pydantic==0.28" alterado para "pydantic==0.30".
- Atualização pras versões `1.0b1` e `1.0b2` requer testes e observação do comportamento do `async-worke`r. Alterações nas novas versões incluem reorganização no parsing de URLs, mudanças em defaults do `BaseSettings` e em como a classe lê variáveis de ambiente, alterações na classe `BaseModel` (modificações em dunder methods `__getattr__`, `__values__` e` __dict__`), entre outras.
Closes #134
> Versão Pydantic atualizada para 0.30 em setup.py

- CONTRIBUTING.md
- asyncworker/conf.py
- asyncworker/consumer.py
- docs-src/userguide/handlers/rabbitmq.rst
- docs/userguide/handlers/rabbitmq.html
- tests/rabbitmq/test_rabbitmq_consumer.py
O bulk_flush_interval estava sendo pego do arquivo de configuração ao invés da configuração da rota. Fiz a modificação para pegar da configuração da rota (passado no app.route), como está na documentação.
> Obtain bulk_flush_interval from route options

- asyncworker/app.py
- tests/test_app.py
- tests/test_routes.py
Dessa forma podemos ter handlers assim:
```python
class Handler:
async def __call__(self, req: web.Request):
pass
h = Handler()
app.route(...)(h)
```
Closes #155.
> Implementa suporte a um objeto calable como handler

- asyncworker/consumer.py
- asyncworker/easyqueue/queue.py
- asyncworker/options.py
- asyncworker/routes.py
- docs-src/userguide/handlers/rabbitmq.rst
- tests/easyqueue/test_async_queue.py
Estava precisando de uma callback que fosse chamada quando a conexão com o broker falhasse.
Adicionei uma nova opção lá no `_AMQPRouteOptions` e adicionei a chamada à função no `JsonQueue`.
Além disso, habilitei o log caso haja error de conexão no `JsonQueue`; a variável de log não estava definida.
> Callback chamada caso haja erro na conexão com broker

- asyncworker/consumer.py
- tests/rabbitmq/test_rabbitmq_consumer.py
Tenho que acessar um vhost no formato `/bla`, mas o asyncworker remove os `/` à esquerda, então não consigo conectar no vhost correto, recebendo esse erro:
```
"(530, 'NOT_ALLOWED - vhost bla not found')"
```
Esse PR remove a lógica que remove o `/` do nome do vhost.
> Não remove / à esquerda dos vhosts

- Pipfile
- Pipfile.lock
- asyncworker/routes.py
- setup.py
A versão atual é bem antiga, e isso estava me quebrando. Além disso, o fato dela estar pinnada a uma versão específica da lib gerava conflitos de dependência. O que eu fiz foi:
- Atualizar versão no Pipfile e setup.py para qualquer coisa >=0.32.2 e <2.0
- Consertar o código que quebrou com a atualização.
> Atualiza pydantic para 1.4

- asyncworker/conf.py
- asyncworker/metrics/aiohttp_resources.py
- asyncworker/metrics/collectors/base.py
- asyncworker/metrics/collectors/gc.py
- asyncworker/metrics/collectors/platform.py
- asyncworker/metrics/collectors/process.py
- asyncworker/metrics/definitions/amqp.py
- asyncworker/metrics/definitions/http.py
- asyncworker/metrics/registry.py
- asyncworker/metrics/types.py
- examples/metrics.py
- tests/http/test_metrics_endpoint.py
- tests/metrics/test_gc_collector.py
- tests/metrics/test_platform_collector.py
- tests/metrics/test_process_collector.py
Agora todas as métricas importadas de `asyncworker.metrics.types.*` e
também de `asyncoworker.metrics.*` estão vinculadas ao nosso registry
interno.
Adicionado também um namespace padrão.
- ~Preciamos de um novo prefixo que pode escolhido pelo usuário e que será colocado no nome das métricas **internas** expostas por padrão pelo asyncworker?~ Penso que sim. É um prefixo apenas para que as métricas fiquem únicas **por app**. Uma sugestão de nome: `ASYNCWORKER_APPMETRICS_PREFIX`. O valor padrão é vazio. https://github.com/b2wdigital/async-worker/pull/203#issuecomment-629842314
- ~Essa opção seria obrigatória?~ Opcional
Como o prefixo padrão também foi movido para o settings acaba sendo possível mudá-lo com a env `ASYNCWORKER_METRICS_NAMESPACE`. Cabe a nós documentar esse detalhe, ou não. =D
> Associando as métricas ao nosso registry interno

- asyncworker/metrics/types.py
- docs-src/changelog/v0.15.0.rst
- docs-src/userguide/metrics/autoexposed-metrics.rst
Mostra como atualizar para a versão onde temos a possibilidade de
expor métricas no formato do Prometheus
> Documentando como atualizar um projeto asyncworker

- examples/rabbitmq.py
Estava usando o parametro errado para o prefech.
O model de AMQPConnection espera `prefetch` e estávamos passando
`prefetch_count`.
Mas o model está configurado para ignorar atributos
adicionais (Comportamento padrão do pydantic). Levei um debugando até perceber que o problema era esse.
Talvez faça sentido termos modelos mais estritos, assim esse tipo de
problema não seria nem possível de acontecer.
> Corrigindo exemplo do rabbitmq

- asyncworker/app.py
- tests/test_routes.py
Atualmente permitimos que um handler síncrono seja registrado e o erro
só vai acontecer em runtime. Nesse commit validamos isso para que o erro
aconteca o mais cedo possível.
> Raise TypeError se um handler não for async

- .github/workflows/pull-request.yaml
Agora pelo menos o `pipenv install --dev` funciona no python 3.9. 🎉 
Ainda falta ajustar os testes, mas faremos isso depois. =D
> Instala libxml2-dev e xslt-dev para o Github Actions

- Pipfile
- Pipfile.lock
O versão atual (`4.5.0`) não instala no python 3.10-dev (3.10.0). Já a
`4.6.1` instala. Esse update já é um passo no caminho da compatibilidade
com python 3.10.x
> Atualizando lxml para 4.6.1

- .github/workflows/pull-request.yaml
- Pipfile
- Pipfile.lock
- asyncworker/task_runners.py
- tests/task_runners/test_scheduled.py
Closes #238.
Esse é o teste que pensei em escrever:
```python
async def test_current_task_compatiple_with_py36_plus(self):
clock = asynctest.MagicMock()
clock.__aiter__.return_value = range(3)
def _current_task():
return self.task
with patch.multiple(self.task_runner, clock=clock), patch.object(
asyncio, "current_task", _current_task
), patch.object(
asyncio.Task, "current_task", _current_task, create=True
):
await self.task_runner._run()
self.assertEqual(set(), self.task_runner.running_tasks)
```
A ideia é simular a existência/não-existência de cada uma das APIs. Temos alguns problemas.
- O upload do coverage não pe feito duas vezes, ou seja, o codeclimate rejeita o segunto upload de um mesmo commit. Nesse caso vamos ajustar o workflow para fazer upload apenas em um dos pythons, pode ser …
> Ajusa o uso do current_task()

- .github/workflows/release.yaml
O Relase do binário do codeclimate está quebrado. O arquivo `https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64` foi publicado como um binário do MacOS.
```
file test-reporter-latest-linux-amd64 
test-reporter-latest-linux-amd64: Mach-O 64-bit x86_64 executable
```
A github action que usamos (https://github.com/paambaati/codeclimate-action) pega sempre a versão `latest`, ou seja, está pegando a versão quebrada. Já existe um PR pra fazer ser possível escolher a versão do runner (assim um build quebrado por parte do codeclimate não atrapalhará tanto da próxima vez). O PR está aqui: https://github.com/paambaati/codeclimate-action/pull/276
Enquanto o PR não for mergeado ou o codeclimate não corrigir o build quebrado …
> Remove wheel publish

- Pipfile
- Pipfile.lock
- asyncworker/routes.py
- docs-src/changelog/v0.17.0.rst
- setup.py
Estávamos com a restrição em `< 2.0`. A versão `1.8` foi lançada há menos de uma semana e com essa versão instalada
alguns testes nem são coletados pelo pytest. Esse é um exemplo de erro:
```
itests/test_rabbitmq_consumer.py:5: in <module>
from asyncworker import App, RouteTypes
asyncworker/__init__.py:1: in <module>
from asyncworker.app import App
asyncworker/app.py:9: in <module>
from asyncworker.http.entrypoints import HTTPEntryPointImpl
asyncworker/http/entrypoints.py:3: in <module>
from asyncworker.entrypoints import _extract_async_callable, EntrypointInterface
asyncworker/entrypoints.py:6: in <module>
from asyncworker.routes import RouteHandler
asyncworker/routes.py:70: in <module>
class Route(Model, abc.ABC):
pydantic/main.py:287: in pydantic.main.ModelMetaclass.__new__
??? …
```
> Restringindo versão do pydantic para <= 1.8

- asyncworker/__init__.py
- asyncworker/decorators.py
- asyncworker/http/decorators.py
- asyncworker/types/resolver.py
- asyncworker/utils.py
- docs-src/changelog/v0.18.0.rst
- docs-src/devguide/custom-decorators.rst
- tests/http/test_http_decorators.py
- tests/test_decorators.py
- tests/test_utils.py
Esse PR muda a forma como um decorator para um handler deve ser escrito. A forma anterior impedia que dois decorators (que dependessem da assinatura original do handler) fossem aplicados a um mesmo handler. Um exemplo:
O decorator `@parse_path` precisa conhecer o handler **original** para que possa extrair corretamente os valores do request a passar para o `TypesRegistry`. Isso significava que esse decorator deveria ficar **sempre** imediatamente acima do handler que estava sendo decorado.
O problema isso é que a partir do momento que você precisa decorar seu handler com quaisquer outros decorators você teria que lembrar dessa regra, ou seja, sempre deixar o `@parse_path` mais perto do handler.
Isso piorava quando você tinha dois decorators que precisavam conhecer a assinatura original. …
> Nova interface para decorators de handlers

- asyncworker/decorators.py
- asyncworker/http/decorators.py
- asyncworker/http/entrypoints.py
- asyncworker/http/types.py
- asyncworker/types/registry.py
- asyncworker/typing/__init__.py
- asyncworker/utils.py
- docs-src/changelog/v0.19.1.rst
- docs-src/userguide/handlers/http/doc.rst
- docs-src/userguide/handlers/http/index.rst
- examples/http_api.py
- tests/http/test_pathparam_type.py
- tests/test_decorators.py
- tests/test_utils.py
- tests/types/test_arg_resolver.py
- tests/types/test_registry.py
- tests/typing/test_typing_functions.py
Esse PR implementa a possibilidade de um handler receber parametros do path do request. Ele também deprecia, oficialmente, o uso do decorator `@parse_path`.
Efetivamente essa implementação permite transformar um handler assim:
```python
@app.http.get(["/by_id/{_id}"])
@parse_path
async def by_id(_id: int):
return web.json_response({"_id": _id})
```
Em um handler assim:
```python
from asyncworker.http.types import PathParam
@app.http.get(["/by_id/{_id}"])
async def by_id(_id: PathParam[int]):
value = await _id.unpack()
return web.json_response({"_id": value})
```
Mais detalhes sobre a ideia por traś dessa implementação estão no #114. E o racional por trás do `.unpack()` está aqui: [#114 comment](https://github.com/b2wdigital/async-worker/issues/114#issuecomment-573776467)
Closes #136 
- …
> Implementação do typehint PathParam[T]
