- asyncworker/consumer.py
- tests/test_consumer.py
> 12 :: Melhorando performance do processamento de mensagens

- Pipfile
- Pipfile.lock
- README.md
- asyncworker/utils.py
- tests/test_utils.py
> #2 :: Timeit

- asyncworker/rabbitmq/message.py
Não precisa setar os defaults como `None`, basta olhar primeiro o
`_final_action`.
Sugestão do @lemosflavio.
> Simplificando o lógica de action do RabbitMQMessage

- .gitignore
- Pipfile
- Pipfile.lock
Adição de denpendência e ignore para pytest_cache do python 3
> Adição de async-worker como dependência no Pipfile

- README.md
- asyncworker/utils.py
- tests/test_utils.py
> 24 :: Múltiplas chamadas a Timeit

- Pipfile
- Pipfile.lock
O que fiz foi apenas re-instalar o codecov, que é quem puxa o requests.
> Atualizando requests

- Pipfile
- Pipfile.lock
- asyncworker/rabbitmq/connection.py
- setup.py
- tests/rabbitmq/test_rabbitmq_connections.py
> #69 :: easyqueue==2.0.0

- .travis.yml
> #72 Adding travis deployment integration

- README.md
> chore: Add pypi badge

- setup.py
* #29 (PR #30) Configuração de formatador e linter;
* #45 (PR #62) implementação de tasks recorrentes (`@app.run_every()`);
* #36 (PR #59) Possibilidade do handler ter acesso à conexão com a fila, para publicar mensagens;
* #72 (PR #73) Deploy automático no travis;
* #58 (PR #79) Adicionando badge da versão no pypi;
* PR #80 Adição de mais typehints no projeto.
> Version bump. 0.7.0

- setup.py
Modificações da versão 0.8.0
* Atualização do `aiohttp` para `3.5.4`; https://github.com/B2W-BIT/async-worker/pull/84
* Buxfixes na implementação interna do ClockTicker; https://github.com/B2W-BIT/async-worker/pull/88
* Implementação do `FLUSH_INTERVAL` para handlers com suporte a `BULK`; https://github.com/B2W-BIT/async-worker/pull/88
Commits de difetença entre as versões `0.7.0` e `0.8.0`: https://github.com/B2W-BIT/async-worker/compare/release/0.7.0...release/0.8.0?expand=1
> Release version: 0.8.0

- asyncworker/consumer.py
- asyncworker/easyqueue/queue.py
- asyncworker/rabbitmq/connection.py
- asyncworker/rabbitmq/message.py
- tests/easyqueue/base.py
- tests/easyqueue/test_async_queue.py
- tests/rabbitmq/test_rabbitmq_connections.py
- tests/rabbitmq/test_rabbitmq_consumer.py
> #89 - easyqueue renames

- asyncworker/base.py
- tests/test_base.py
> Change order of on_startup handlers call

- .github/CODEOWNERS
Dessa forma todos os PRs já vão os reviewers automaticamente
> Adicionando codeowners

- asyncworker/base.py
- asyncworker/signals/base.py
> #108 Fixing shutdown event handling

- asyncworker/types/resolver.py
- tests/signals/handlers/test_http.py
- tests/types/test_arg_resolver.py
> Ignorando return annotation

- README.md
Renomeamos a org de b2w-bit para b2wdigital
> Mudando o link do repo, agora que a org foi renomeada

- asyncworker/connections.py
- asyncworker/easyqueue/queue.py
- tests/easyqueue/test_async_queue.py
- tests/rabbitmq/test_rabbitmq_connections.py
Here new parameters: https://github.com/Polyconseil/aioamqp/blob/master/aioamqp/channel.py#L672
> Enabling new parameters from aioamqp

- docs-src/changelog/v0.11.0.rst
- docs-src/userguide/index.rst
Na 0.11.0 mudamos o construtor da app principal
Closes #180
> Documentando breaking change da versao 0.11.0

- .github/release-drafter.yml
https://github.com/release-drafter/release-drafter
Ajustei as labels para:
- bug
- docs
- breaking-change
- feature
Depois colocamos mais se acharmos necessário.
> Adicionando config do Release Drafter

- setup.py
Isso faz com que o readme seja exibido corretamente na página do projeto
no pypi: https://pypi.org/project/async-worker/
> Coloca README.md no long_description

- asyncworker/easyqueue/queue.py
- tests/easyqueue/test_async_queue.py
Aparentente não estava sendo usado pra nada.
> Removendo atributo max_message_length

- asyncworker/easyqueue/queue.py
- tests/easyqueue/test_async_queue.py
Só tinha teste usando esse código.
> Removendo stop_consumer() que não era usado.

- Pipfile
- Pipfile.lock
- docs-src/conf.py
Com esse plugin podemos fazer :pr:`N` para linkar para um PR
do projeto no Github.
> Instala sphinx-issues

- Pipfile
- Pipfile.lock
Closes #241
Recomendação do dependabot.
https://github.com/b2wdigital/async-worker/pull/241
> Atualiza cryptography==3.2
